export const apiURL = (data1, data2) => {
    return {
        LOGIN                       : "https://be_my_ticket_api-1-u4160695.deta.app/login/",
        REGISTER                    : "https://be_my_ticket_api-1-u4160695.deta.app/register/",
        TIKET_STASIUN               : "https://be_my_ticket_api-1-u4160695.deta.app/show_tiket/",
        ORDER_TIKET                 : "https://be_my_ticket_api-1-u4160695.deta.app/order_tiket/",
        PROFILE_USER_DATA           : `https://be_my_ticket_api-1-u4160695.deta.app/profile/${data1}`,
        UPDATE_PROFILE_USER_DATA    : `https://be_my_ticket_api-1-u4160695.deta.app/update/${data1}`,
        MY_ARTIKEL                  : `https://be_my_ticket_api-1-u4160695.deta.app/artikel_of_user/${data1}`,
        DELETE_ARTIKEL              : `https://be_my_ticket_api-1-u4160695.deta.app/delete_artikel/${data1}/${data2}`,
        POST_NEW_ARTIKEL            : `https://be_my_ticket_api-1-u4160695.deta.app/post_artikel/${data1}`,
        UPDATE_THUMBNAIL_ARTIKEL    : `https://be_my_ticket_api-1-u4160695.deta.app/update_thumbnail_artikel/${data1}/${data2}`,
        QUESTIONS_FOR_TOPUP         : "https://be_my_ticket_api-1-u4160695.deta.app/questions-for-topup/",
        QUESTIONS_ANSWER_CHECKER    : "https://be_my_ticket_api-1-u4160695.deta.app/questions-for-topup/answer-checker",
        USER_SALDO_CHECKER          : `https://be_my_ticket_api-1-u4160695.deta.app/saldo/?userID=${data1}`,
        UPDATE_USER_SALDO           : `https://be_my_ticket_api-1-u4160695.deta.app/topup/${data1}/${data2}`,
        UPDATE_ARTIKEL              : `https://be_my_ticket_api-1-u4160695.deta.app/update_artikel/${data1}/${data2}`,
        CHANGE_PASSWORD             : `https://be_my_ticket_api-1-u4160695.deta.app/changepassword/${data1}`,
        UPLOAD_IMAGE                : "https://be_my_ticket_api-1-u4160695.deta.app/image/",
        UPDATE_PROFILE_PICTURE      : `https://be_my_ticket_api-1-u4160695.deta.app/profile_picture/${data1}`,
        UPDATE_PROFILE_BANNER       : `https://be_my_ticket_api-1-u4160695.deta.app/banner_picture/${data1}`,
        CHECK_USER_PASSWORD         : "https://be_my_ticket_api-1-u4160695.deta.app/checkcurrentpassword/",
        MY_TIKET_LIST               : `https://be_my_ticket_api-1-u4160695.deta.app/tiket_saya/${data1}`,
        LIKE_OF_ARTIKEL_BY_USER     : `https://be_my_ticket_api-1-u4160695.deta.app/show-artikel-like/${data1}/${data2}/`,
        LIKE_THE_ARTIKEL            : `https://be_my_ticket_api-1-u4160695.deta.app/like-artikel/${data1}/${data2}/`,
        TOTAL_LIKE_A_ARTIKEL        : `https://be_my_ticket_api-1-u4160695.deta.app/total-like-artikel/${data1}`,
        PUBLIC_COMMENT              : `https://be_my_ticket_api-1-u4160695.deta.app/comment-public/${data1}`,
        TOTAL_COMMENT_A_ARTIKEL     : `https://be_my_ticket_api-1-u4160695.deta.app/total-comment-artikel/${data1}`,
        SEND_COMMENT_PUBLIC         : "https://be_my_ticket_api-1-u4160695.deta.app/send-comment-public/",
        COMMENT_ARTIKEL_BY_USER     : `https://be_my_ticket_api-1-u4160695.deta.app/show-artikel-comment/${data1}/${data2}`,
        ARTIKEL_BECOME_COMMENT      : `https://be_my_ticket_api-1-u4160695.deta.app/artikel-comment/${data1}`,
        EDIT_PUBLIC_COMMENT         : "https://be_my_ticket_api-1-u4160695.deta.app/edit-comment-public/",
        DELETE_COMMENT_PUBLIC       : `https://be_my_ticket_api-1-u4160695.deta.app/delet-comment-public/${data1}`,
        SHOW_ALL_ARTIKEL            : "https://be_my_ticket_api-1-u4160695.deta.app/artikelall/",
        BUY_TIKET                   : "https://be_my_ticket_api-1-u4160695.deta.app/pembelian_tiket/",
        TIKET_PURCHASED_BY_USER     : `https://be_my_ticket_api-1-u4160695.deta.app/bought_tiket/${data1}`,
        CHAT_WEBSOCKET              : `ws://127.0.0.1:8000/chat/${data1}`
    }
}